version: "3.3"

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_PASSWORD}
  
  backend:
    build: ./backend
    volumes:
      - .:/code
    ports:https://www.zeit.de/index
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    expose:
      - ${BACKEND_PORT}
    stdin_open: true
    tty: true
    command: python3 manage.py runserver 0.0.0.0:8000
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_NAME=${POSTGRES_NAME}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
    depends_on:
      - db
    container_name: backend
  
  frontend:
    build: ./frontend
    ports:
      - "${ALTERNATIVE_PORT}:${FRONTEND_PORT}"
    expose:
      - ${ALTERNATIVE_PORT}
    environment:
      - NODE_ENV=${DEBUG}
      - TARGET=${TARGET}
    depends_on:
      - backend
      - db
    command: npm start
    links:
      - backend

volumes:
  postgres_data:
