version: "3.7"

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_PASSWORD}
  
  backend:
    build: ./backend
    volumes:
      - .:/code
    ports:
      - "${APP_SERVER_PORT}:${APP_SERVER_PORT}"
    expose:
      - ${APP_SERVER_PORT}
    stdin_open: true
    tty: true
    command: python3 manage.py runserver 0.0.0.0:8000
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_NAME=${POSTGRES_NAME}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
    depends_on:
      - db
    container_name: backend
  
  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "${REACT_APP_PORT}:${REACT_APP_PORT}"
  #   environment:
  #     - NODE_ENV=${DEBUG}
  #     - REACT_APP_PORT=${REACT_APP_PORT}
  #     - TARGET=${TARGET}
  #   expose:
  #     - ${REACT_APP_PORT}
  #   depends_on:
  #     - backend
  #     - db
  #   command: npm start
  #   links:
  #     - backend

volumes:
  postgres_data: