version: "3.7"

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
  
  backend:
    build: ./backend
    volumes:
      - .:/code
    ports:
      - "${APP_SERVER_PORT}:${APP_SERVER_PORT}"
    expose:
      - ${APP_SERVER_PORT}
    stdin_open: true
    tty: true
    command: python3 manage.py runserver 0.0.0.0:8000
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_NAME=postgres
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - SECRET_KEY=foo
      - DEBUG=1
    depends_on:
      - db
  
  frontend:
    build: ./frontend
    ports:
      - "${REACT_APP_PORT}:${REACT_APP_PORT}"
    environment:
      - NODE_ENV=development
      - REACT_APP_PORT=${REACT_APP_PORT}
    expose:
      - ${REACT_APP_PORT}
    depends_on:
      - backend
      - db
    command: npm start
    links:
      - backend

volumes:
  postgres_data: